# Generated by Django 3.2.16 on 2024-05-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodAdditives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_title', models.IntegerField()),
                ('common_title', models.CharField(max_length=125)),
                ('category', models.CharField(max_length=125)),
                ('description', models.TextField()),
                ('is_dangerous', models.BooleanField()),
            ],
        ),
    ]
