# Generated by Django 3.2.16 on 2024-05-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodadditives',
            options={'verbose_name': 'пищевая добавка', 'verbose_name_plural': 'Пищевые добавки'},
        ),
        migrations.AddField(
            model_name='foodadditives',
            name='is_not_informative',
            field=models.BooleanField(default=False, verbose_name='нет информации по добавке'),
        ),
        migrations.AlterField(
            model_name='foodadditives',
            name='category',
            field=models.CharField(max_length=125, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='foodadditives',
            name='common_title',
            field=models.CharField(max_length=125, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='foodadditives',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='foodadditives',
            name='e_title',
            field=models.IntegerField(verbose_name='номер E'),
        ),
        migrations.AlterField(
            model_name='foodadditives',
            name='is_dangerous',
            field=models.BooleanField(verbose_name='опасна'),
        ),
    ]
