# Generated by Django 3.2.16 on 2024-05-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20240515_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodadditives',
            name='is_not_informative',
        ),
        migrations.AddField(
            model_name='foodadditives',
            name='is_informative',
            field=models.BooleanField(default=True, verbose_name='есть информация по добавке'),
        ),
    ]
